# Site settings
title: WProsdocimo Fotografia
email: wilson@wprosdocimo.com.br
description: > # this means to ignore newlines until "baseurl:"
  Um blog de fotografia, ideias e experimentos...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wprosdocimo.fot.br" # the base hostname & protocol for your site
twitter_username: wprosdocimo
github_username:  wprosdocimo
facebook_username: wprosdocimo

# Build settings
markdown: kramdown

# Author Data
author :
  name : Wilson Luiz Prosdocimo
  email : wilson@wprosdocimo.com.br
  tumblr: wprosdocimo
  flickr: wprosdocimo
  github : wprosdocimo
  repository: wprosdocimo.github.io
  twitter : wprosdocimo
  facebook: wprosdocimo
  linkedin: wprosdocimo
  googleplus: wprosdocimo
  pinterest: wprosdocimo